#
# PRODUCTION
#
production:
  adapter: postgresql
  encoding: unicode
  database: gitlabhq_production
  username: git
  password: "123456"
  host: localhost
  # load_balancing:
  #   hosts:
  #     - host1.example.com
  #     - host2.example.com
  #   discover:
  #     nameserver: 1.2.3.4
  #     port: 8600
  #     record: secondary.postgresql.service.consul
  #     interval: 300

